/**
 * LLMTXT Generator
 *
 * Generates llms.txt file from all published content for AI engine optimization.
 * Detects when llms.txt is missing or outdated.
 *
 * Part of Week 5 - Smart Optimization Scanner
 * Reference: https://llmstxt.org/
 */

/**
 * LLMTXT Opportunity
 */
export interface LLMTXTOpportunity {
  type: "UPLOAD_LLMTXT";
  pageUrl: string; // Site root URL
  pageTitle: string;
  priorityScore: number;
  estimatedImpact: "high" | "medium" | "low";
  detectionDetails: {
    rule: "missing_or_outdated_llmtxt";
    findings: {
      currentLLMTXTExists: boolean;
      lastLLMTXTUpdate?: number; // timestamp
      totalPublishedArticles: number;
      articlesNotInLLMTXT?: number;
      llmtxtUrl?: string;
    };
    suggestedFix: {
      generateNewLLMTXT: boolean;
      llmtxtContent: string;
      uploadPath: string;
    };
  };
}

/**
 * LLMTXT Entry (one per article)
 */
interface LLMTXTEntry {
  title: string;
  url: string;
  summary: string;
  keywords: string[];
  lastUpdated?: string; // ISO date
}

/**
 * Check if llms.txt exists at site root
 */
async function checkLLMTXTExists(siteUrl: string): Promise<{
  exists: boolean;
  content?: string;
  lastModified?: number;
}> {
  try {
    const llmtxtUrl = new URL("/llms.txt", siteUrl).href;
    const response = await fetch(llmtxtUrl);

    if (response.ok) {
      const content = await response.text();
      const lastModified = response.headers.get("last-modified");
      const lastModifiedTimestamp = lastModified ? new Date(lastModified).getTime() : undefined;

      return {
        exists: true,
        content,
        lastModified: lastModifiedTimestamp,
      };
    }

    return { exists: false };
  } catch (error) {
    return { exists: false };
  }
}

/**
 * Generate llms.txt content from articles
 *
 * Format:
 * ```
 * # Site Name
 *
 * > Site tagline or description
 *
 * ## Articles
 *
 * ### Article Title
 * URL: https://example.com/article
 * Summary: Brief description
 * Keywords: keyword1, keyword2
 * Last Updated: 2024-01-15
 *
 * ---
 * ```
 */
function generateLLMTXTContent(
  siteName: string,
  siteDescription: string,
  articles: any[]
): string {
  let content = `# ${siteName}\n\n`;
  content += `> ${siteDescription}\n\n`;
  content += `## Published Content\n\n`;
  content += `This file provides a structured overview of all content on ${siteName} for AI engines and language models.\n\n`;

  // Add each article
  articles.forEach((article, index) => {
    const title = article.title || "Untitled";
    const url = article.publishedUrl || "";
    const summary = article.summary || article.metaDescription || "No summary available";
    const keywords = Array.isArray(article.keywords) ? article.keywords.join(", ") : "";
    const lastUpdated = article.lastUpdatedAt
      ? new Date(article.lastUpdatedAt).toISOString().split("T")[0]
      : "";

    content += `### ${title}\n\n`;
    content += `**URL**: ${url}\n\n`;
    content += `**Summary**: ${summary}\n\n`;

    if (keywords) {
      content += `**Keywords**: ${keywords}\n\n`;
    }

    if (lastUpdated) {
      content += `**Last Updated**: ${lastUpdated}\n\n`;
    }

    // Separator between articles
    if (index < articles.length - 1) {
      content += `---\n\n`;
    }
  });

  // Add footer
  content += `\n---\n\n`;
  content += `*This file is automatically generated and updated. Last generated: ${new Date().toISOString().split("T")[0]}*\n`;

  return content;
}

/**
 * Detect LLMTXT opportunities
 *
 * @param siteUrl - Root URL of the site
 * @param siteName - Name of the site
 * @param siteDescription - Tagline/description
 * @param articles - All published articles
 * @returns Array of LLMTXT opportunities detected
 */
export async function detectLLMTXTOpportunities(
  siteUrl: string,
  siteName: string,
  siteDescription: string,
  articles: any[]
): Promise<LLMTXTOpportunity[]> {
  const opportunities: LLMTXTOpportunity[] = [];

  // Only check published articles
  const publishedArticles = articles.filter((a) => a.status === "published");

  if (publishedArticles.length === 0) {
    return opportunities;
  }

  // Check if llms.txt exists
  const llmtxtCheck = await checkLLMTXTExists(siteUrl);

  let needsUpdate = false;
  let articlesNotInLLMTXT = 0;

  if (!llmtxtCheck.exists) {
    // No llms.txt file - definitely need to create one
    needsUpdate = true;
  } else {
    // llms.txt exists - check if it's outdated
    const daysSinceUpdate = llmtxtCheck.lastModified
      ? (Date.now() - llmtxtCheck.lastModified) / (1000 * 60 * 60 * 24)
      : Infinity;

    // Update if:
    // 1. Not updated in 30 days
    // 2. Articles not in current llms.txt
    if (daysSinceUpdate > 30) {
      needsUpdate = true;
    }

    // Count articles not in current llms.txt
    if (llmtxtCheck.content) {
      publishedArticles.forEach((article) => {
        if (!llmtxtCheck.content!.includes(article.publishedUrl || article.title)) {
          articlesNotInLLMTXT++;
        }
      });

      if (articlesNotInLLMTXT > 0) {
        needsUpdate = true;
      }
    }
  }

  if (!needsUpdate) {
    return opportunities;
  }

  // Generate new llms.txt content
  const llmtxtContent = generateLLMTXTContent(siteName, siteDescription, publishedArticles);

  // Calculate priority score
  let priorityScore = 70; // Base score (always important)

  // No llms.txt at all = urgent
  if (!llmtxtCheck.exists) {
    priorityScore = 95;
  }

  // Many articles missing = higher priority
  if (articlesNotInLLMTXT > 5) {
    priorityScore += 10;
  }

  // Cap at 100
  priorityScore = Math.min(priorityScore, 100);

  // Estimated impact
  const estimatedImpact: "high" | "medium" | "low" = !llmtxtCheck.exists ? "high" : "medium";

  // Create opportunity
  opportunities.push({
    type: "UPLOAD_LLMTXT",
    pageUrl: siteUrl,
    pageTitle: `${siteName} - LLMTXT Update`,
    priorityScore,
    estimatedImpact,
    detectionDetails: {
      rule: "missing_or_outdated_llmtxt",
      findings: {
        currentLLMTXTExists: llmtxtCheck.exists,
        lastLLMTXTUpdate: llmtxtCheck.lastModified,
        totalPublishedArticles: publishedArticles.length,
        articlesNotInLLMTXT,
        llmtxtUrl: llmtxtCheck.exists ? new URL("/llms.txt", siteUrl).href : undefined,
      },
      suggestedFix: {
        generateNewLLMTXT: true,
        llmtxtContent,
        uploadPath: "/llms.txt",
      },
    },
  });

  return opportunities;
}

/**
 * Export llms.txt content to file (for download)
 */
export function exportLLMTXTFile(
  siteName: string,
  siteDescription: string,
  articles: any[]
): { filename: string; content: string } {
  const content = generateLLMTXTContent(siteName, siteDescription, articles);

  return {
    filename: "llms.txt",
    content,
  };
}

/**
 * Validate llms.txt content format
 */
export function validateLLMTXT(content: string): {
  valid: boolean;
  errors: string[];
  warnings: string[];
} {
  const errors: string[] = [];
  const warnings: string[] = [];

  // Check for site name (# heading)
  if (!content.match(/^#\s+.+$/m)) {
    errors.push("Missing site name (# heading at the top)");
  }

  // Check for description (> blockquote)
  if (!content.match(/^>\s+.+$/m)) {
    warnings.push("Missing site description (> blockquote)");
  }

  // Check for at least one article entry
  if (!content.match(/^###\s+.+$/m)) {
    errors.push("No article entries found (### headings)");
  }

  // Check for URLs
  if (!content.match(/\*\*URL\*\*:/m)) {
    warnings.push("No article URLs found");
  }

  const valid = errors.length === 0;

  return { valid, errors, warnings };
}
